version: "3.9"
services:
  redis:
    image: "redis/redis-stack"
    container_name: "redis-stack"
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --appendonly yes
        --protected-mode no
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
